server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8&Timezone=GMT%2B8 #驱动为8以上的版本需要添添加时区
    username: root
    password: QaYs4910
    type: com.alibaba.druid.pool.DruidDataSource #Druid连接池